# Cargo configuration for optimized builds
# These settings balance binary size optimization with reasonable build times

[profile.release]
# Optimize for size rather than speed (important for game engine plugins)
opt-level = "z"

# Use thin LTO for good optimization with faster build times (2-3x faster than full LTO)
# thin = faster than full LTO, still provides most benefits
lto = "thin"

# Allow some parallelization for faster builds (4-6x faster than codegen-units=1)
# 4 units is a good balance between optimization and build time
# codegen-units = 4

# Strip debug symbols from the binary
strip = true

# Use abort instead of unwind for panics (smaller binary)
panic = "abort"

[profile.dev]
# Faster compilation in development
opt-level = 0
