name: CI Build Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build for ${{ matrix.platform }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: Windows x64
            lib_name: gdserial.dll
            use_cross: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            platform: Windows ARM64
            lib_name: gdserial.dll
            use_cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: Linux x64
            lib_name: libgdserial.so
            use_cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            platform: Linux ARM64
            lib_name: libgdserial.so
            use_cross: true
          - os: macos-13
            target: x86_64-apple-darwin
            platform: macOS Intel
            lib_name: libgdserial.dylib
            use_cross: false
          - os: macos-15
            target: aarch64-apple-darwin
            platform: macOS Apple Silicon
            lib_name: libgdserial.dylib
            use_cross: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies (Linux native builds)
      if: matrix.os == 'ubuntu-latest' && matrix.use_cross == false
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}

    - name: Install cross for cross-compilation
      if: matrix.use_cross == true
      run: cargo install cross --git https://github.com/cross-rs/cross
      shell: bash

    - name: Clean cargo cache for cross-compilation
      if: matrix.use_cross == true
      run: cargo clean
      shell: bash

    - name: Build release (native)
      if: matrix.use_cross == false
      run: cargo build --release --target ${{ matrix.target }}
      shell: bash

    - name: Build release (cross-compilation)
      if: matrix.use_cross == true
      run: cross build --release --target ${{ matrix.target }}
      shell: bash

    - name: Verify build artifact exists
      run: |
        if [ -f "target/${{ matrix.target }}/release/${{ matrix.lib_name }}" ]; then
          echo "✅ Build artifact found: target/${{ matrix.target }}/release/${{ matrix.lib_name }}"
          ls -lh "target/${{ matrix.target }}/release/${{ matrix.lib_name }}"
        else
          echo "❌ Build artifact not found!"
          exit 1
        fi
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gdserial-${{ matrix.target }}-test
        path: target/${{ matrix.target }}/release/${{ matrix.lib_name }}
        retention-days: 7

  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
    - name: Check build results
      run: |
        echo "## Build Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All platform builds completed. Check individual job results above." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Tested Platforms:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Windows x64" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Windows ARM64" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Linux x64" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Linux ARM64" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ macOS Intel (x86_64)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ macOS Apple Silicon (ARM64)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "> This is a test build. No release will be created." >> $GITHUB_STEP_SUMMARY
